### ISSUE TITLE
执行打包命令报错”文件t1.txt不在根目录下“

### ISSUE THREAD

**Issue by chenshu-byte** [EtherDream/mini-program-pack#1]
执行打包命令报错”文件t1.txt不在根目录下“，但是目录下有这个文件
![image](https://github.com/EtherDream/mini-program-pack/assets/140032839/cdddf20c-02c0-46ad-bbd5-2cbf1095a363)

**Comment by EtherDream** [comment]
我知道原因了，windows 路径用的是反斜杠。我修复下。

**Comment by EtherDream** [comment]
修复了，你更新下 mini-program-pack 试试。

**Comment by chenshu-byte** [comment]
好的，感谢
